services:
  web-server:
    build: ./go-app/.
    container_name: web-server
    ports:
      - "8080:8080"
    networks:
      - network

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on: 
      - web-server
    ports: 
      - "80:80"
    networks:
      - network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  network:
